image: alpine

before_script:
  - apk update && apk add build-base lua5.3 luarocks

stages:
  - test

lua_test:
  stage: test
  script:
    - lua5.3 -v
    - lua5.3 test.lua
    - cat test_scripts/test_populate.txt | lua repl.lua --memory
