version: "3.7"
services:
  leader:
    build: .
    command: lua5.3 server.lua --name compose-leader --role leader
    volumes:
      - .:/code/
  follower-1:
    build: .
    command: lua5.3 server.lua --name compose-follower-1 --role follower --leader_host leader
    depends_on:
      - leader
    volumes:
      - .:/code/
  follower-2:
    build: .
    command: lua5.3 server.lua --name compose-follower-2 --role follower --leader_host leader
    depends_on:
      - leader
    volumes:
      - .:/code/
  test:
    build: .
    command: lua5.3 test.lua
    volumes:
      - .:/code/
